export const SET_AUTHOR = 'SET_AUTHOR'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_COUNTFLOW = 'SET_COUNTFLOW'

export const SET_SINGOUT_LOGIN = "SET_SINGOUT_LOGIN"

export const SET_PATH_URL = 'SET_PATH_URL'

export const SET_ACCESSTOKEN = 'SET_ACCESSTOKEN'
